# Generated by Django 5.0.7 on 2024-08-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carmodel_body_type_alter_carmodel_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('id',)},
        ),
    ]
