# Generated by Django 5.0.7 on 2024-08-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('-id',)},
        ),
    ]
